version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mongodb+srv://narinderlalotora2434_db_user:TQo7BmsIiTB30kzR@cluster0.jjvyq3s.mongodb.net/?appName=Cluster0
      - PORT=5000
      - JWT_SECRET=supersecret_jwt_key_production
      - NODE_ENV=production
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api
    depends_on:
      - server
    restart: always
